# Generated by Django 5.1.1 on 2024-11-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_quantiy_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='Nike Shoe', max_length=250),
        ),
    ]
