# Generated by Django 5.1.1 on 2024-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='Nike Shoe', max_length=300),
        ),
    ]
