# Generated by Django 5.1.1 on 2024-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_location',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], max_length=20),
        ),
    ]
